import cloth from "../Orange_Cloth.png";
const ListingData = [
  {
    id: "1",
    category: "men",
    type: "TShirts",
    src: cloth,
    title: "Cloth1",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    colour: "red",
    rating: "4.5/5",
    price: "34",
    recommended: true,
    lastUpdated: "Jan 01, 2001",
  },
  {
    id: "2",
    category: "women",
    type: "Dresses",
    src: cloth,
    title: "Cloth2",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "90",
    recommended: true,
    lastUpdated: "Jan 01, 2001,  11:59",
  },
  {
    id: "3",
    category: "kids",
    type: "TShirts",
    src: cloth,
    title: "Cloth3",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "54",
    recommended: true,
    lastUpdated: "2019/01/01",
  },
  {
    id: "4",
    category: "men",
    type: "Jeans",
    src: cloth,
    title: "Cloth5",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "blue",
    rating: "4.5/5",
    price: "223",
    recommended: false,
    lastUpdated: "2022/01/01",
  },
  {
    id: "5",
    category: "men",
    type: "jackets",
    src: cloth,
    title: "Cloth6",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "343",
    recommended: true,
    lastUpdated: "2021/04/01",
  },
  {
    id: "6",
    category: "men",
    type: "jackets",
    src: cloth,
    title: "Cloth6",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "234",
    recommended: false,
    lastUpdated: "2017/01/01",
  },
  {
    id: "7",
    category: "men",
    type: "tshirts",
    src: cloth,
    title: "jacket6",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "78",
    recommended: true,
    lastUpdated: "2011/01/01",
  },
  {
    id: "8",
    category: "men",
    type: "sweaters",
    src: cloth,
    title: "Cloth1",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "88",
    recommended: false,
    lastUpdated: "2018/01/01",
  },
  {
    id: "9",
    category: "men",
    type: "sweaters",
    src: cloth,
    title: "Cloth7",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "87",
    recommended: false,
    lastUpdated: "2021/09/11",
  },
  {
    id: "10",
    category: "women",
    type: "tshirts",
    src: cloth,
    title: "Cloth1",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    colour: "red",
    rating: "4.5/5",
    price: "12",
    recommended: false,
    lastUpdated: "2021/09/10",
  },
  {
    id: "11",
    category: "women",
    type: "Dresses",
    src: cloth,
    title: "Cloth2",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "90",
    recommended: false,
    lastUpdated: "2021/09/09",
  },
  {
    id: "12",
    category: "kids",
    type: "Shorts",
    src: cloth,
    title: "Cloth1",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "99",
    recommended: false,
    lastUpdated: "2009/01/01",
  },
  {
    id: "13",
    category: "women",
    type: "Tops",
    src: cloth,
    title: "Cloth8",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "120",
    recommended: true,
    lastUpdated: "2009/01/01",
  },
  {
    id: "14",
    category: "kids",
    type: "Jeans",
    src: cloth,
    title: "Cloth3",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "190",
    lastUpdated: "2009/01/01",
  },
  {
    id: "15",
    category: "kids",
    type: "Dress",
    src: cloth,
    title: "Cloth9",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "349",
    recommended: false,
    lastUpdated: "2010/01/01",
  },
  {
    id: "16",
    category: "women",
    type: "Tops",
    src: cloth,
    title: "jacket8",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "74",
    recommended: false,
    lastUpdated: "2012/01/01",
  },
  {
    id: "17",
    category: "women",
    type: "jeans",
    src: cloth,
    title: "Cloth2",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "99",
    recommended: false,
    lastUpdated: "2013/01/01",
  },
  {
    id: "18",
    category: "women",
    type: "TShirts",
    src: cloth,
    title: "Cloth8",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    color: "red",
    rating: "4.5/5",
    price: "90",
    lastUpdated: "2014/01/01",
  },
  {
    id: "19",
    category: "men",
    type: "TShirts",
    src: cloth,
    title: "Cloth1",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    colour: "red",
    rating: "4.5/5",
    price: "34",
    recommended: true,
    lastUpdated: "2012/01/01",
  },
  {
    id: "20",
    category: "men",
    type: "TShirts",
    src: cloth,
    title: "Cloth1",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    colour: "red",
    rating: "4.5/5",
    price: "30",
    recommended: true,
    lastUpdated: "2015/01/01",
  },
  {
    id: "21",
    category: "men",
    type: "TShirts",
    src: cloth,
    title: "Cloth1",
    desc: "Small detail regarding clothas dasdsads adsadssa sadasda sdsad  sadasdasd sadsadsd sadasdsad",
    colour: "red",
    rating: "4.5/5",
    price: "839",
    recommended: true,
    lastUpdated: "2016/01/01",
  },
];

export default ListingData;
